# Generated by Django 5.2.6 on 2025-09-13 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_item_max_amount_item_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='settings',
        ),
        migrations.AddField(
            model_name='item',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
