# Generated by Django 4.x on 2025-09-13
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('bidding', '0003_remove_item_settings_item_min_amount'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='item',
            name='min_amount',
        ),
    ]
